/** @format */

import { call, put } from 'redux-saga/effects';
import { TypeExtraArguments } from '../types';

import { ChronologyAction, ChronologyApiResponse } from './types';

import { apiGetChronologies } from '../api';
import { STATUS_VALID } from '../utils/costants/status';
import {
  actionGetChronologyRequest,
  actionGetChronologySuccess,
  actionGetChronologyFailure,
} from './actions';

const fakeData: ChronologyApiResponse = {
  status: 'OK',
  payload: {
    movements: [
      {
        bankProfileId: '',
        tppUid: '',
        sobjectId: '123',
        propBankTransactionCode: '',
        descriptionStructured: '',
        valueDate: 1552431600000,
        accountId: '18503628',
        amount: 1,
        beneficiaryIban: 'IT78I0339512900052747025630',
        beneficiaryName: 'LNMIP IYYDG',
        bookingDate: null,
        bookingNumber: null,
        bookingTotalAmount: null,
        category: 'others',
        chargedAccountNumber: '0052531384000',
        chargedProductNumber: null,
        contactName: null,
        createdDate: 1570624678665,
        creditor: null,
        cro: '32846068204',
        currency: null,
        emittente: null,
        executer: 'GAWLZF IMNSILES',
        executionDate: '09/10/2019',
        expiry: null,
        fiscalCode: null,
        formattedDebitCardNumber: null,
        formattedDebitCardPAN: null,
        hasSplit: null,
        isIncome: false,
        mcc: null,
        memo: null,
        merchant: null,
        mobileNumber: null,
        movUpdateDate: null,
        movementId: '285806',
        numeroRiBa: null,
        oldCategory: null,
        oldSubCategory: null,
        operationType: 'bon',
        paymentDescription: 'GIRO',
        paymentType: null,
        piva: null,
        productInfo: {
          productType: 'ACCOUNT',
          bankProfile: '-1',
          productId: '18503628',
          productParent: null,
        },
        receivingAccountNumber: '0052747025630',
        receivingProductNumber: null,
        recurrent: null,
        recurrentTag: null,
        reference: 'GIRO',
        sender: null,
        status: 'EXECUTED',
        subCategory: 'othersOthers',
        telcoOperator: null,
        typology: null,
        userId: '8664291',
        vehicleLicensePlate: null,
        vehicleType: null,
      },
      {
        bankProfileId: '',
        tppUid: '',
        sobjectId: '123',
        propBankTransactionCode: '',
        descriptionStructured: '',
        valueDate: 1552431600000,
        accountId: '18503628',
        amount: 1,
        beneficiaryIban: 'IT78I0339512900052747025630',
        beneficiaryName: 'LNMIP IYYDG',
        bookingDate: null,
        bookingNumber: null,
        bookingTotalAmount: null,
        category: 'others',
        chargedAccountNumber: '0052531384000',
        chargedProductNumber: null,
        contactName: null,
        createdDate: 1570624678665,
        creditor: null,
        cro: '32846068204',
        currency: null,
        emittente: null,
        executer: 'GAWLZF IMNSILES',
        executionDate: '09/10/2019',
        expiry: null,
        fiscalCode: null,
        formattedDebitCardNumber: null,
        formattedDebitCardPAN: null,
        hasSplit: null,
        isIncome: false,
        mcc: null,
        memo: null,
        merchant: null,
        mobileNumber: null,
        movUpdateDate: null,
        movementId: '285806',
        numeroRiBa: null,
        oldCategory: null,
        oldSubCategory: null,
        operationType: 'bon',
        paymentDescription: 'GIRO',
        paymentType: null,
        piva: null,
        productInfo: {
          productType: 'ACCOUNT',
          bankProfile: '-1',
          productId: '18503628',
          productParent: null,
        },
        receivingAccountNumber: '0052747025630',
        receivingProductNumber: null,
        recurrent: null,
        recurrentTag: null,
        reference: 'GIRO',
        sender: null,
        status: 'EXECUTED',
        subCategory: 'othersOthers',
        telcoOperator: null,
        typology: null,
        userId: '8664291',
        vehicleLicensePlate: null,
        vehicleType: null,
      },
      {
        bankProfileId: '',
        tppUid: '',
        sobjectId: '123',
        propBankTransactionCode: '',
        descriptionStructured: '',
        valueDate: 1552431600000,
        accountId: '18503628',
        amount: 1,
        beneficiaryIban: 'IT78I0339512900052747025630',
        beneficiaryName: 'LNMIP IYYDG',
        bookingDate: null,
        bookingNumber: null,
        bookingTotalAmount: null,
        category: 'school',
        chargedAccountNumber: '0052531384000',
        chargedProductNumber: null,
        contactName: null,
        createdDate: 1570624678665,
        creditor: null,
        cro: '32846068204',
        currency: null,
        emittente: null,
        executer: 'GAWLZF IMNSILES',
        executionDate: '09/10/2019',
        expiry: null,
        fiscalCode: null,
        formattedDebitCardNumber: null,
        formattedDebitCardPAN: null,
        hasSplit: null,
        isIncome: false,
        mcc: null,
        memo: null,
        merchant: null,
        mobileNumber: null,
        movUpdateDate: null,
        movementId: '285806',
        numeroRiBa: null,
        oldCategory: null,
        oldSubCategory: null,
        operationType: 'bon',
        paymentDescription: 'GIRO',
        paymentType: null,
        piva: null,
        productInfo: {
          productType: 'ACCOUNT',
          bankProfile: '-1',
          productId: '18503628',
          productParent: null,
        },
        receivingAccountNumber: '0052747025630',
        receivingProductNumber: null,
        recurrent: null,
        recurrentTag: null,
        reference: 'GIRO',
        sender: null,
        status: 'EXECUTED',
        subCategory: 'othersOthers',
        telcoOperator: null,
        typology: null,
        userId: '8664291',
        vehicleLicensePlate: null,
        vehicleType: null,
      },
    ],
    categories: [{ alias: 'home', label: 'casa' }],
    operationTypes: [{ alias: 'bon', label: 'Bonifico' }],
    totalRetrieved: 55,
  },
  errors: [],
};

export function* sagas(
  action: ChronologyAction,
  extraArguments: TypeExtraArguments,
) {
  yield put(
    actionGetChronologyRequest({
      data: null,
      isLoading: true,
      isLoaded: false,
      errors: null,
    }),
  );

  try {
    const { payload, status, errors }: ChronologyApiResponse = yield call(
      apiGetChronologies,
      action.params || {},
      extraArguments.BASE_URL,
    );


    return yield put(
      actionGetChronologySuccess({
        data: fakeData.payload,
        isLoaded: true,
        isLoading: false,
        errors,
      }),
    );
  } catch (error) {
    return yield put(
      actionGetChronologyFailure({
        data: null,
        isLoaded: false,
        isLoading: false,
        errors: [error],
      }),
    );
  }
}
